<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Deletando Usuário';
$url   = $this->url('pessoa', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Você tem certeza que quer apagar o usuário?
    -> <?= $this->escapeHtml($pessoa->nome) ?>
    <?= $this->escapeHtml($pessoa->sobrenome) ?>
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $pessoa->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Sim" />
    <input type="submit" class="btn btn-success" name="del" value="Não" />
</div>
</form>