<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Editando Informações da Pessoa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$pessoa = $form->get('nome');
$pessoa->setAttribute('class', 'form-control');
$pessoa->setAttribute('placeholder', 'Pessoa nome');

$sobrenome = $form->get('sobrenome');
$sobrenome->setAttribute('class', 'form-control');
$sobrenome->setAttribute('placeholder', 'Sobrenome');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$situacao = $form->get('situacao');
$situacao->setAttribute('class', 'form-control');
$situacao->setAttribute('placeholder', 'Situacao');



$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('pessoa', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($pessoa) ?>
    <?= $this->formElement($pessoa) ?>
    <?= $this->formElementErrors()->render($pessoa, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($sobrenome) ?>
    <?= $this->formElement($sobrenome) ?>
    <?= $this->formElementErrors()->render($sobrenome, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($situacao) ?>
    <?= $this->formElement($situacao) ?>
    <?= $this->formElementErrors()->render($situacao, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();